# Generated by Django 4.1 on 2022-08-24 11:30

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_tutorial_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 24, 13, 30, 55, 879335),
                verbose_name="date published",
            ),
        ),
    ]
